#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = hyprpolkitagent

#exec-once = awww-daemon
#exec-once = mpvpaper '*' ~/Pictures/wallpapers/animated/rivendell.mp4
#exec-once = gslapper -o "loop" '*' /home/agust/Pictures/wallpapers/animated/rivendell.mp4
exec-once = gslapper -o "loop" '*' ~/Pictures/wallpapers/animated/rivendell_1080p.mp4

exec-once = waybar

exec-once = swaync
exec-once = gnome-keyring-daemon --start --components=secrets

exec-once = gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "gruvbox-dark-gtk"
