dwindle {
    #pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vrr = 2
}

cursor {
    # Crucial for NVIDIA cards to prevent micro-stuttering during cursor updates
    no_hardware_cursors = false
}

render {
    direct_scanout = 1
}
