##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule = match:class ^(gamescope)$, fullscreen on


windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}


windowrule {
    name = vscode-opacity
    match:class = ^code$

    opacity = 0.91 0.91
}

windowrule {
    name = vesktop
    match:class = ^(vesktop)$

    opacity = 0.89 0.89
}

windowrule {
    name = thunar-glass
    match:class = ^thunar$

    opacity = 0.85 0.85
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
    
}


windowrule {
    name = gslapper-perf-override
    match:class = ^(gslapper)$

    no_blur = true
    no_shadow = true
    opaque = true
    no_anim = true
}




# Game rules : 


windowrule {
    name = global-steam-gaming
    match:class = ^(steam_app_.*)$
    
    immediate = on
    no_blur = true
    no_shadow = true
}

windowrule {
    name = global-heroic-and-xwayland-gaming
   match:class = ^(XWayland)$
    match:fullscreen = 1
    
    immediate = on
    no_blur = true
    no_shadow = true
}

